name=WGHAVG
version=0.0.1
author=Anton Holgersson
maintainer=Anton Holgersson
sentence=Weighted average calculator based on some simple functions.
paragraph=The NMEA0183 library feature: NMEA0183->NMEA2000 interface
category=Data Processing
url=
architectures=*