name=WGHAVG
version=0.0.1
author=Anton Holgersson
maintainer=Anton Holgersson
sentence=Weighted average calculator based on some simple functions.
paragraph=
category=Data Processing
url=https://github.com/0xHolgersson/WGHAVG
architectures=*
